core: 
  location: Office
  logfile: sensorlog.log
  alertsenabled: true
  snsarn: arn:aws:sns:us-west-2:623709041819:sherniottopic
  #polling interval is in seconds
  pollinginterval: 10
  displaymode: lcdrgbbacklight
  configuredsensors:
    - name: loudness
      port: 1
      unit: notsure
    - name: gas
      port: 2
      unit: notsure
    - name: tempandhumidity
      port: 7
      unit: notsure
#    - dust

loudness: 
  # Uses an analog port so if port was 0 it would A0
  port: 1

gas:
  # Uses an analog port
  port: 2

dust:
  # this is fixed at port d2
  port: 2

tempandhumidity:
  #Uses a digital port so if the port was 3 it would D3
  #Apparently the only port you can use is port 4 
  port: 7



