core: 
  location: Office
  logfile: sensorlog.log
  alertsenabled: true
  snsarn: arn:aws:sns:us-west-2:623709041819:sherniottopic
  #polling interval is in seconds
  pollinginterval: 10
  displaymode: lcdrgbbacklight
  configuredsensors:
    - name: loudness
      port: 1
      unit: notsure
    - name: gas
      port: 2
      unit: notsure
    - name: tempandhumidity
      port: 7
      unit: notsure
#    - dust


aws:
  host: puthosthere
  rootCAPath: apath
  cognitoIdentityPoolID: something
